operations/api/urls.py
from django.conf.urls import include, url
from django.conf import settings
import views


urlpatterns = [
    url(r'^/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^get_vehicle_info/', views.get_vehicle_info),
    url(r'^push_agent_data/', views.push_agent_data),
    url(r'^push_region_data/', views.push_region_data),
    url(r'^push_branch_data/', views.push_branch_data),
]

operations/fleet/urls.py
from django.conf.urls import url, handler400, handler403, handler404, handler500
from . import views
from . models import VehicleMaintenance, InsuranceClaim, RenewLicenceDisk, FuelAllocation, FuelTransfer

handler400 = 'fleet.views.handler400'
handler403 = 'fleet.views.handler403'
handler404 = 'fleet.views.handler404'
handler500 = 'fleet.views.handler500'

urlpatterns = [
    url(r'^fleet/add/vehicle/$', views.addvehicle, name='addvehicle'), 
    url(r'^get/from/trf/$', views.getFromFuelTrfDetails, name='get_fromtrf'),
    url(r'^get/to/trf/$', views.getToFuelTrfDetails, name='get_totrf'),
    url(r'^validate/driver/$', views.validateDriver, name='validate_driver'),   
    url(r'^fleet/edit/vehicle/(?P<vehicle_id>\-{0,1}\d+$)', views.editvehicle, name='editvehicle'),
    url(r'^fleet/view/vehicle/(?P<vehicle_id>\-{0,1}\d+$)', views.viewvehicle, name='viewvehicle'),   
    url(r'^fleet/view/vehicle-details/(?P<vehicle_id>\-{0,1}\d+$)', views.viewvehicleDetails, name='viewvehicleDetails'),     
    url(r'^fleet/view/vehicles-list/$', views.vehiclesList, name='vehiclesList'),

    url(r'^fleet/edit/driving-licence/(?P<trans_id>\-{0,1}\d+$)', views.editDrivingLicence, name='edit_drivinglicence'),
    url(r'^fleet/view/driving-licences-list/$', views.drivingLicencesList, name='view_drivinglicences'),
    url(r'^fleet/view/driver-profile/(?P<driver_id>\-{0,1}\d+$)', views.viewDriverProfile, name='view_driverprofile'), 
    
    url(r'^fleet/allocate/vehicle/(?P<vehicle_id>\-{0,1}\d+$)', views.allocatevehicle, name='allocatevehicle'),
    url(r'^allocate/vehicle/(?P<vehicle_id>\-{0,1}\d)/(?P<driver_id>\-{0,1}\d+$)', views.allocatevehicle_redirected, name='allocatevehicle_redirected'),
    url(r'^fleet/edit/vehicle-allocation/(?P<trans_id>\-{0,1}\d+$)', views.editallocatevehicle, name='editallocatevehicle'),
    url(r'^fleet/view/vehicle-allocation/(?P<trans_id>\-{0,1}\d+$)', views.viewallocatevehicle, name='viewallocatevehicle'),
    url(r'^fleet/view/vehicle-allocations-list/$', views.fleetAllocationsList, name='fleetAllocationsList'),

    url(r'^fleet/add/service-booking/(?P<vehicle_id>\-{0,1}\d+$)', views.bookservice, name='bookservice'),
    url(r'^fleet/edit/service-booking/(?P<trans_id>\-{0,1}\d+$)', views.editbookservice, name='editbookservice'),
    url(r'^fleet/view/service-booking/(?P<trans_id>\-{0,1}\d+$)', views.viewbookservice, name='viewbookservice'),
    url(r'^fleet/view/service-bookings-list/$', views.servicebookingsList, name='servicebookingsList'),

    url(r'^fleet/add/traffic-fine/(?P<vehicle_id>\-{0,1}\d+$)', views.trafficfines, name='trafficfines'),
    url(r'^fleet/edit/traffic-fine/(?P<trans_id>\-{0,1}\d+$)', views.edittrafficfines, name='edittrafficfines'),
    url(r'^fleet/view/traffic-fine/(?P<trans_id>\-{0,1}\d+$)', views.viewtrafficfines, name='viewtrafficfines'),
    url(r'^fleet/view/traffic-fines-list/$', views.trafficfinesList, name='trafficfinesList'),

    url(r'^fleet/add/vehicle-inspection/(?P<vehicle_id>\-{0,1}\d+$)', views.mileagelog, name='mileagelog'),
    url(r'^fleet/edit/vehicle-inspection/(?P<trans_id>\-{0,1}\d+$)', views.editmileagelog, name='editmileagelog'),
    url(r'^fleet/view/vehicle-inspection/(?P<trans_id>\-{0,1}\d+$)', views.viewmileagelog, name='viewmileagelog'),
    url(r'^fleet/view/vehicle-inspections-list/$', views.mileagelogList, name='mileagelogList'),

    url(r'^fleet/add/vehicle-maintenance/(?P<vehicle_id>\-{0,1}\d+$)', views.vehiclemaintenance, name='vehiclemaintenance'),
    url(r'^fleet/edit/vehicle-maintenance/(?P<trans_id>\-{0,1}\d+$)', views.editvehiclemaintenance, name='editvehiclemaintenance'),
    url(r'^fleet/view/vehicle-maintenance/(?P<trans_id>\-{0,1}\d+$)', views.viewvehiclemaintenance, name='viewvehiclemaintenance'),
    url(r'^fleet/view/vehicle-maintenance-list/$', views.vehiclemaintenanceList, name='vehiclemaintenanceList'),
   
    url(r'^fleet/requisition/vehicle/maintenance/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':VehicleMaintenance}, name='requisition_vehiclemaintenance'),
    url(r'^fleet/requisition/vehicle/insurance/excess/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':InsuranceClaim}, name='requisition_insuranceclaimexcess'),    
    url(r'^fleet/requisition/vehicle/licencing/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':RenewLicenceDisk}, name='requisition_vehiclelicencing'),
    url(r'^fleet/requisition/vehicle/fuel/allocation/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':FuelAllocation}, name='requisition_vehiclefuelallocation'),
    url(r'^fleet/requisition/vehicle/fuel/transfer/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':FuelTransfer}, name='requisition_vehiclefueltransfer'),
    url(r'^fleet/requisition/vehicle/trafficfine/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':VehicleMaintenance}, name='requisition_vehicletrafficfine'),

    url(r'^fleet/requisition/item/(?P<obj_id>\-{0,1}\d+$)', views.requisition_item, name='requisition_item'),
    url(r'^fleet/view/requisition/(?P<obj_id>\-{0,1}\d+$)', views.view_requisition, name='view_requisition'),
   
    url(r'^fleet/add/licence-disk-renewal/(?P<vehicle_id>\-{0,1}\d+$)', views.renewlicencedisk, name='renewlicencedisk'),
    url(r'^fleet/edit/licence-disk-renewal/(?P<trans_id>\-{0,1}\d+$)', views.editrenewlicencedisk, name='editrenewlicencedisk'),
    url(r'^fleet/view/licence-disk-renewal/(?P<trans_id>\-{0,1}\d+$)', views.viewrenewlicencedisk, name='viewrenewlicencedisk'),
    url(r'^fleet/view/licence-disk-renewals-list/$', views.licenceDiskRenewalList, name='licenceDiskRenewalList'),
    
    url(r'^fleet/add/vehicle-incident/(?P<vehicle_id>\-{0,1}\d+$)', views.vehicleincidences, name='vehicleincidences'),
    url(r'^fleet/edit/vehicle-incident/(?P<trans_id>\-{0,1}\d+$)', views.editvehicleincidences, name='editvehicleincidences'),
    url(r'^fleet/view/vehicle-incident/(?P<trans_id>\-{0,1}\d+$)', views.viewvehicleincidences, name='viewvehicleincidences'),
    url(r'^fleet/view/vehicle-incidences-list/$', views.incidencesList, name='incidencesList'),

    url(r'^fleet/add/vehicle-claim/(?P<vehicle_id>\-{0,1}\d+$)', views.addVehicleClaim, name='addVehicleClaim'),
    url(r'^fleet/view/vehicle-claim(?P<trans_id>\-{0,1}\d+$)', views.editVehicleClaim, name='viewVehicleClaim'),
    url(r'^fleet/edit/vehicle-claim(?P<trans_id>\-{0,1}\d+$)', views.viewVehicleClaim, name='editVehicleClaim'),   
    url(r'^fleet/view/vehicle-claims-list/$', views.vehicleClaimsList, name='vehicleClaimsList'), 

    url(r'^fleet/fuelcard/$', views.fuelcard, name='fuelcard'), 
    url(r'^fleet/allocate/fuel/(?P<vehicle_id>\-{0,1}\d+$)', views.allocatefuel, name='allocatefuel'),
    url(r'^fleet/edit/allocate/fuel/(?P<trans_id>\-{0,1}\d+$)', views.editallocatefuel, name='editallocatefuel'),

    url(r'^fleet/fueltransfer/$', views.fuelTransfer, name='fuel_transfer'), 

    url(r'^fleet/tripLog/Imports/(?P<vehicle_id>\-{0,1}\d+$)', views.tripLogImports, name='tripLogImports'),
    url(r'^fleet/loadtriplog/(?P<trip_id>\-{0,1}\d+$)', views.load_trip_log, name='load_trip_log'),

    url(r'^fleet/page_carousel/$', views.page_carousel, name='page_carousel'),  
    url(r'^fleet/get_fuel_card/$', views.get_fuel_card, name='get_fuel_card'),
    url(r'^fleet/get_employee/$', views.get_employee, name='get_employee'), 
    url(r'^fleet/get_vehicle/$', views.get_vehicle, name='get_vehicle'),
    url(r'^fleet/get_region/$', views.get_region, name='get_region'),

    url(r'^fleet/reports/current_drivers/$', views.rpt_current_drivers, name='rpt_current_drivers'), 
    url(r'^fleet/reports/vehicle_allocations/$', views.rpt_vehicle_allocations, name='rpt_vehicle_allocations'), 
    url(r'^fleet/reports/vehicle_fuel_allocations/$', views.rpt_vehicle_fuel_allocations, name='rpt_vehicle_fuel_allocations'), 
    url(r'^fleet/reports/vehicle_mileages/$', views.rpt_vehicle_mileages, name='rpt_vehicle_mileages'), 
    url(r'^fleet/reports/mileage_aggregates/$', views.rpt_mileage_aggregates, name='rpt_mileage_aggregates'), 
    url(r'^fleet/reports/driver_mileages/$', views.rpt_driver_mileages, name='rpt_driver_mileages'),
    url(r'^fleet/reports/driver_vehicle_allocations/$', views.rpt_driver_vehicle_allocations, name='rpt_driver_vehicle_allocations'),
    url(r'^fleet/reports/driver_fuel_allocations/$', views.rpt_driver_fuel_allocations, name='rpt_driver_fuel_allocations'),
    url(r'^fleet/reports/service_due/$', views.rpt_service_due, name='rpt_service_due'),
    url(r'^fleet/reports/service_overdue/$', views.rpt_service_overdue, name='rpt_service_overdue'),
    url(r'^fleet/reports/licence_disks_due/$', views.rpt_licence_disks_due, name='rpt_licence_disks_due'),
    url(r'^fleet/reports/licence_disks_expired/$', views.rpt_licence_disks_expired, name='rpt_licence_disks_expired'),
    url(r'^fleet/reports/vehicle_traffic_fines/$', views.rpt_vehicle_traffic_fines, name='rpt_vehicle_traffic_fines'),
    url(r'^fleet/reports/driver_traffic_fines/$', views.rpt_driver_traffic_fines, name='rpt_driver_traffic_fines'),    
    url(r'^fleet/reports/vehicle_maintenance/$', views.rpt_vehicle_maintenance, name='rpt_vehicle_maintenance'),
    url(r'^fleet/reports/vehicle_insurance_claims/$', views.rpt_vehicle_insurance_claims, name='rpt_vehicle_insurance_claims'),
    url(r'^fleet/reports/vehicle_incidences/$', views.rpt_vehicle_incidences, name='rpt_vehicle_incidences'),
    url(r'^fleet/reports/driver_incidences/$', views.rpt_driver_incidences, name='rpt_driver_incidences'),

    
    url(r'^fleet/authorizations/$', views.authorizations, name='authorizations'),
    url(r'^fleet/comments/$', views.comments, name='comments'),

        
    url(r'^fleet/redirect_from_comment/$', views.redirect_from_comment, name='redirect_from_comment'),    
]

operations/operations/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from django_js_reverse.views import urls_js
from models import RegionAutoComplete,DistrictAutoComplete

urlpatterns = [
    url(r'^region_autocomplete/$', RegionAutoComplete.as_view(), name='region_autocomplete'),
    url(r'^district_autocomplete/$', DistrictAutoComplete.as_view(), name='district_autocomplete'),    
    url(r'^$', views.home, name='home'),
    url(r'^jsreverse/$', urls_js, name='js_reverse'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout,{'next_page':'/'}, name='logout'),

    url(r'^about/$', views.about, name='about'),
    url(r'^users$', views.users, name='users'),
    url(r'^users/fleet-admins/(?P<fleet_administrators>\d+)/$', views.users, name='fleet_admins'),
    url(r'^user/add/$', views.user_edit, name='user_add'),
    url(r'^user/edit/(?P<user_id>\d+)/$', views.user_edit, name='user_edit'),
    
    
    url(r'^', include('fleet_management.urls', namespace='fleetmanagement')),
    url(r'^', include('employees.urls', namespace='employees')), 
    url(r'^', include('facilities.urls', namespace='facilities')),   
    url(r'^', include('assets.urls', namespace='assets')),
    url(r'^', include('api.urls', namespace='api')),

    url(r'^regions$', views.view_regions, name='view_regions'),
    url(r'^branches$', views.view_branches, name='view_branches'),

    url(r'^downloads/$', views.downloads_list, name="view_downloads"),
    url(r'^downloads/(?P<file_id>\d+)/$', views.file_download_task, name="file_download"),

    url(r'^tickets$', views.view_tickets, name='view_tickets'),
    url(r'^tickets/add$', views.edit_ticket, name='add_ticket'),
    url(r'^tickets/edit(?P<ticket_id>\d+)/$', views.edit_ticket, name='edit_ticket'),

    url(r'^service_provider/uploads$', views.service_provider_uploads, name='service_provider_uploads'),
    url(r'^districts/uploads$', views.district_uploads, name='district_uploads'),

    url(r'^accounts/user_profile/(?P<user_id>\-{0,1}\d+$)', views.user_profile, name='user_profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

operations/templates/fleet/reports/rpt_driver_fuel_allocations.html
{% extends "base.html" %}
{% load staticfiles%}
{% load humanize %}
{% block javascript %}
<script>
  $(function() {
    $(".auto-complete-vehicle").autocomplete({
    source: "{% url 'fleet:get_vehicle' %}",
    minLength: 2});

    $(".auto-complete-driver").autocomplete({
    source: "{% url 'fleet:get_employee' %}",
    minLength: 2});

    $(".auto-complete-region").autocomplete({
    source: "{% url 'fleet:get_region' %}",
    minLength: 2});

  });

</script>


{% endblock %}

{% block content%}
<div class="transparency">
<form method="POST" action="">
{% csrf_token %}
<h1>{{title}}</h1>   
  <table class="table table-hover  table-fixed">              
    <tr>
      <th>{{filter_form.region}}</th>
      <th>{{filter_form.driver}}</th>
      <th>{{filter_form.start_date}}</th>
      <th>{{filter_form.end_date}}</th>
      <th><input class="btn btn-warning" id="filter_logs" name="filter_logs" type="submit" value="Search"/>
           <a class="btn btn-warning" href="{% url 'fleet:rpt_driver_fuel_allocations' %}" type="submit">Refresh</a>
          <input class="btn btn-warning" id="report" name="report" type="submit" value="Export CSV"/></th>
      </tr>                     
    </table>
  {% for employee, values in tran_dict.items %}				
  <h4> {{ employee }}</h4>

  <table class="table table-hover table-striped ">							     
    <tr style="background-color: #808080;">				
      <tr>				
		<th>Allocation date</th>
		<th>Transaction Type</th>
		<th>Vehicle</th>
		<th style="width: 18%">Make and Model</th>				
		<th>Fuel Card</th>
		<th>Fuel OB</th>
		<th>Fuel Amount</th>
		<th>Fuel CB</th>
		
	</tr>
      
    </tr>
    
    {% for val in values.transactions %}
    <tr>
      <td>{{ val.allocation_date }}</td>
      <td>{{ val.allocation_type }}</td>					
      <td>{{ val.vehicle }}</td>
      <td>{{ val.make_n_model }}</td>
      <td>{{ val.fuel_card }} </td>     					
      <td>{{ val.fuel_ob|floatformat:2|intcomma }} </td>
      <td>{{ val.allocated|floatformat:2|intcomma }}</td>
      <td>{{ val.fuel_cb|floatformat:2|intcomma }} </td>      
    </tr>
    {% endfor %}
    
    <tr style="background-color: #808080;">
      <th>Totals</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>				
      <th>{{ values.totals.allocated|floatformat:2|intcomma }}</th>
      <th></th>
    </tr>
    
  </table>
  {% endfor %}
  </form>
</div>
{% endblock %}

operations/templates/fleet/reports/rpt_driver_incidences.html
{% extends "base.html" %}
{% load staticfiles%}
{% block javascript %}
{% load humanize %}
<script>
  $(function() {
    $(".auto-complete-vehicle").autocomplete({
    source: "{% url 'fleet:get_vehicle' %}",
    minLength: 2});

    $(".auto-complete-driver").autocomplete({
    source: "{% url 'fleet:get_employee' %}",
    minLength: 2});

    $(".auto-complete-region").autocomplete({
    source: "{% url 'fleet:get_region' %}",
    minLength: 2});
  });

</script>


{% endblock %}

{% block content%}
<div class="transparency panel-body">
<form method="POST" action=""> 
{% csrf_token %}
<h1>{{title}}</h1>  
  <table class="table table-hover  table-fixed">              
      <tr>
        <th>{{filter_form.region}}</th>
        <th>{{filter_form.driver}}</th>
        <th>{{filter_form.start_date}}</th>
        <th>{{filter_form.end_date}}</th>
        <th><input class="btn btn-warning" id="filter_logs" name="filter_logs" type="submit" value="Search"/>
            <a class="btn btn-warning" href="{% url 'fleet:rpt_driver_incidences' %}" type="submit">Refresh</a>
            <input class="btn btn-warning" id="report" name="report" type="submit" value="Export CSV"/></th>
      </tr>
    </table>
  {% for employee, values in tran_dict.items %}				
  <h4>{{ employee }}</h4>

  <table class="table table-hover ">							     
   <tr style="background-color: #808080;">                     
        <th>Vehicle</th>
        <th>Date</th>
        <th>Incident Type</th>
        <th>Location</th>
        <th style="width:30%">Description</th>
        <th>Damage Extent</th>
      </tr> 
    
    {% for val in values.transactions %}
    <tr>
      <td>{{ val.incident_date }}</td>					
      <td>{{ val.vehicle }}</td>
      <td>{{ val.incident_type }} </td>
      <td>{{ val.location }}</td>
      <td>{{ val.description }} </td>					
      <td>{{ val.status }} </td>
      
    </tr>
    {% endfor %}  
    
    
  </table>
  {% endfor %}
  </form>
</div>
{% endblock %}

operations/templates/fleet/reports/rpt_driver_mileages.html
{% extends "base.html" %}
{% load staticfiles%}
{% load humanize %}
{% block javascript %}

<script>
  $(function() {
    $(".auto-complete-vehicle").autocomplete({
    source: "{% url 'fleet:get_vehicle' %}",
    minLength: 2});

    $(".auto-complete-driver").autocomplete({
    source: "{% url 'fleet:get_employee' %}",
    minLength: 2}); 

    $(".auto-complete-region").autocomplete({
    source: "{% url 'fleet:get_region' %}",
    minLength: 2});
  });

</script>


{% endblock %}

{% block content%}
<div class="transparency">
<form method="POST" action="">
{% csrf_token %}
<h1>{{title}}</h1>   
  <table class="table table-hover table-striped  table-fixed">              
    <tr>
     <th>{{filter_form.region}}</th>
      <th>{{filter_form.driver}}</th>
      <th>{{filter_form.start_date}}</th>
      <th>{{filter_form.end_date}}</th>
      <th><input class="btn btn-warning" id="filter_logs" name="filter_logs" type="submit" value="Search"/>
          <a class="btn btn-warning" href="{% url 'fleet:rpt_driver_mileages' %}" type="submit">Refresh</a>
          <input class="btn btn-warning" id="report" name="report" type="submit" value="Export CSV"/></th>
          </tr>
          </tr>
        </table>
  {% for employee, values in tran_dict.items %}				
  <h4> {{ employee }}</h4>

  <table class="table table-hover ">							     
    <tr>				
      <th>Log date</th>				
      <th >Vehicle</th>
      <th>Starting KM</th>
      <th>Current KM</th>
      <th>Mileage</th>				
      <th>Fuel OB</th>
      <th>Fuel Used</th>
      <th>Fuel CB</th>
      <th>Status </th>
      
    </tr>
    
    {% for val in values.transactions %}
    <tr>
      <td>{{ val.log_date }}</td>					
      <td>{{ val.vehicle }}</td>
      <td>{{ val.starting_km|floatformat:2|intcomma }} </td>
      <td>{{ val.current_km|floatformat:2|intcomma }}</td>
      <td>{{ val.mileage|floatformat:2|intcomma }} </td>					
      <td>{{ val.fuel_ob|floatformat:2|intcomma }} </td>
      <td>{{ val.fuel_used|floatformat:2|intcomma }}</td>
      <td>{{ val.fuel_cb|floatformat:2|intcomma }} </td>
      <td>{{ val.status }} </td>
    </tr>
    {% endfor %}
    
    <tr style="background-color: #808080;">
      <th></th>
      <th>Totals</th>
      <th></th>
      <th></th>
      <th>{{ values.totals.mileage|floatformat:2|intcomma }}</th>
      <th></th>				
      <th>{{ values.totals.fuel_used|floatformat:2|intcomma }}</th>
      <th></th>
    </tr>
    
  </table>
  {% endfor %}
  </form>
</div>
{% endblock %}

operations/templates/fleet/reports/rpt_driver_traffic_fines.html
{% extends "base.html" %}
{% load staticfiles%}
{% load humanize %}
{% block javascript %}

<script>
  $(function() {
  $(".auto-complete-vehicle").autocomplete({
  source: "{% url 'fleet:get_vehicle' %}",
  minLength: 2});

  $(".auto-complete-driver").autocomplete({
  source: "{% url 'fleet:get_employee' %}",
  minLength: 2});

  $(".auto-complete-region").autocomplete({
    source: "{% url 'fleet:get_region' %}",
    minLength: 2});

  });

</script>


{% endblock %}

{% block content%}
<div class="transparency">
<form method="POST" action="">
{% csrf_token %}
  <h1>{{title}}</h1>   
  <table class="table table-hover  table-fixed">              
    <tr>
      <th>{{filter_form.region}}</th>
      <th>{{filter_form.driver}}</th>
      <th>{{filter_form.start_date}}</th>
      <th>{{filter_form.end_date}}</th>
      <th><input class="btn btn-warning" id="filter_logs" name="filter_logs" type="submit" value="Search"/>
          <a class="btn btn-warning" href="{% url 'fleet:rpt_driver_traffic_fines' %}" type="submit">Refresh</a>
          <input class="btn btn-warning" id="report" name="report" type="submit" value="Export CSV"/></th></th>
          </tr>
        </table>
  {% for employee, values in tran_dict.items %}				
  <h4> <strong>{{ employee }}</strong></h4>

  <table class="table table-hover table-striped ">							     
    <tr>
      <th>Vehicle</th>  
      <th>Notice Number</th>
      <th>Offence date</th>
      <th>Time</th>
      <th>Due date</th>
      <th style="width: 20%;">Location</th>
      <th>Region</th>
      <th style="width: 20%;">Description</th>
      <th>Amount</th>
      <th></th>
    </tr>   
    
    {% for val in values.transactions %}
    <tr>     				
      <td>{{ val.vehicle }}</td>
      <td>{{ val.notice_number }} </td>
      <td>{{ val.offence_date }}</td>
      <td>{{ val.time }}</td>
      <td>{{ val.due_date }} </td>					
      <td style="width: 20%;">{{ val.location}} </td>
      <td>{{ val.region }}</td>
      <td style="width: 20%;">{{ val.description }}</td>      
      <td>{{ val.amount|floatformat:2|intcomma }} </td>
      <td>{% for item in val.attachs %} 
            <a href= "{{ item.file.url }}" target="top"  data-toggle="" data-toggle="tooltip" data-placement="right" title="Download {{ item.file_name }}"> 
              <i class="fa fa-download" aria-hidden="true"></i>
            </a>
            {% empty %}
             No File
          {% endfor %}</td>      
    </tr>
    {% endfor %}
    
    <tr style="background-color: #808080;">
      <th>Totals</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>				
      <th>{{ values.totals.amount|floatformat:2|intcomma }}</th><th></th>    
    </tr>
    
  </table>
  {% endfor %}
  </form>
</div>
{% endblock %}

operations/templates/fleet/reports/rpt_vehicle_insurance_claims.html
{% extends "base.html" %}
{% load staticfiles%}
{% load humanize %}
{% block javascript %}

  
  	<script>
  		$(function() {
  			$(".auto-complete-vehicle").autocomplete({
				source: "{% url 'fleet:get_vehicle' %}",
	    		minLength: 2});

  			$(".auto-complete-driver").autocomplete({
				source: "{% url 'fleet:get_employee' %}",
	    		minLength: 2});
  		});

	</script>
	

{% endblock %}

{% block content%}
<div class="transparency">
<form method="POST" action="">
{% csrf_token %}
	<h1>{{title}}</h1>
	<input class="btn btn-warning pull-right" id="report" name="report" type="submit" value="Export CSV"/>

	<table class="table table-hover ">							
		<tr>
			<th>Current Driver</th>
			<th>Vehicle</th>								
			<th>Make and Model</th>
			<th>Claims</th>
			<th>Pending</th>
			<th>Finalized</th>
			<th>Rejected</th>
			<th>Total Claims</th>
			<th>Total Excess</th>
		</tr>								
		{% for vehicle in vehicles %}
			<tr>
				<td>{{ vehicle.get_current_driver }}</td>
				<td>{{ vehicle.vehicle }} </td>
				<td>{{ vehicle.make_n_model }} </td>
				<td>{{ vehicle.get_count_claims}}</td>
				<td>{{ vehicle.get_count_claims_pending }}</td>
				<td>{{ vehicle.get_count_claims_finalized }}</td>	
				<td>{{ vehicle.get_count_claims_rejected }}</td>				
				<td>{{ vehicle.get_total_excess }}</td>	
				<td>{{ vehicle.get_total_claims }}</td>															
				
			</tr>										
		{% endfor %}						
	</table>
</form>
</div>
{% endblock %}