operations/api/urls.py
from django.conf.urls import include, url
from django.conf import settings
import views


urlpatterns = [
    url(r'^/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^get_vehicle_info/', views.get_vehicle_info),
    url(r'^push_agent_data/', views.push_agent_data),
    url(r'^push_region_data/', views.push_region_data),
    url(r'^push_branch_data/', views.push_branch_data),
]

operations/assets/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
import views

from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from dal import autocomplete

import views
from fleet_management.autocomplete import *

from .models import *
from employees.models import *
from operations.models import *
from facilities.models import *
from assets.models import *

urlpatterns = [
    url(r'^assets$', views.assets, name='view_assets'),
    url(r'^assets/edit/(?P<asset_id>\d+)/$', views.edit_asset, name='edit_asset'),
    url(r'^assets/add/$', views.edit_asset, name='add_asset'),
    url(r'^get_districts/(?P<region_id>\d+)/$', views.get_districts, name='get_districts'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

operations/employees/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
import views

urlpatterns = [
    url(r'^employees/$', views.employees, name='employees'),
    url(r'^employees/edit/(?P<employee_id>\d+)/$', views.edit_employee, name='edit_employee'),
    url(r'^reports/drivers_licence_expiry$', views.drivers_licence_expiry, name='drivers_licence_expiry'),

]

operations/facilities/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from dal import autocomplete

import views
from fleet_management.autocomplete import *

from .models import *
from employees.models import *
from operations.models import *
from facilities.models import *

urlpatterns = [
    url(r'^stock_items/$', views.stock_items, name='stock_items'),
    url(r'^stock_items/edit/(?P<item_id>\d+)/$', views.edit_stock_item, name='edit_stock_item'),
    url(r'^stock_items/add/$', views.edit_stock_item, name='add_stock_item'),    
    
    url(r'^get_opening_balance/(?P<item_id>\d+)/$', views.get_opening_balance, name='get_opening_balance'),

    url(r'^stock_items/uploads/$', views.stock_items_uploads, name='stock_items_uploads'),

    url(r'^stock_items/transactions/$', views.stock_items_transactions, name='stock_items_transactions'),
    url(r'^stock_items/transactions/edit/(?P<item_id>\d+)/$', views.edit_stock_item_transaction, name='edit_stock_item_transaction'),
    url(r'^stock_items/transactions/add/$', views.edit_stock_item_transaction, name='add_stock_item_transaction'),

    url(r'^stock_item_delete/(?P<item_id>\d+)/$', views.stock_item_delete, name='stock_item_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

operations/fleet/urls.py
from django.conf.urls import url, handler400, handler403, handler404, handler500
from . import views
from . models import VehicleMaintenance, InsuranceClaim, RenewLicenceDisk, FuelAllocation, FuelTransfer

handler400 = 'fleet.views.handler400'
handler403 = 'fleet.views.handler403'
handler404 = 'fleet.views.handler404'
handler500 = 'fleet.views.handler500'

urlpatterns = [
    url(r'^fleet/add/vehicle/$', views.addvehicle, name='addvehicle'), 
    url(r'^get/from/trf/$', views.getFromFuelTrfDetails, name='get_fromtrf'),
    url(r'^get/to/trf/$', views.getToFuelTrfDetails, name='get_totrf'),
    url(r'^validate/driver/$', views.validateDriver, name='validate_driver'),   
    url(r'^fleet/edit/vehicle/(?P<vehicle_id>\-{0,1}\d+$)', views.editvehicle, name='editvehicle'),
    url(r'^fleet/view/vehicle/(?P<vehicle_id>\-{0,1}\d+$)', views.viewvehicle, name='viewvehicle'),   
    url(r'^fleet/view/vehicle-details/(?P<vehicle_id>\-{0,1}\d+$)', views.viewvehicleDetails, name='viewvehicleDetails'),     
    url(r'^fleet/view/vehicles-list/$', views.vehiclesList, name='vehiclesList'),

    url(r'^fleet/edit/driving-licence/(?P<trans_id>\-{0,1}\d+$)', views.editDrivingLicence, name='edit_drivinglicence'),
    url(r'^fleet/view/driving-licences-list/$', views.drivingLicencesList, name='view_drivinglicences'),
    url(r'^fleet/view/driver-profile/(?P<driver_id>\-{0,1}\d+$)', views.viewDriverProfile, name='view_driverprofile'), 
    
    url(r'^fleet/allocate/vehicle/(?P<vehicle_id>\-{0,1}\d+$)', views.allocatevehicle, name='allocatevehicle'),
    url(r'^allocate/vehicle/(?P<vehicle_id>\-{0,1}\d)/(?P<driver_id>\-{0,1}\d+$)', views.allocatevehicle_redirected, name='allocatevehicle_redirected'),
    url(r'^fleet/edit/vehicle-allocation/(?P<trans_id>\-{0,1}\d+$)', views.editallocatevehicle, name='editallocatevehicle'),
    url(r'^fleet/view/vehicle-allocation/(?P<trans_id>\-{0,1}\d+$)', views.viewallocatevehicle, name='viewallocatevehicle'),
    url(r'^fleet/view/vehicle-allocations-list/$', views.fleetAllocationsList, name='fleetAllocationsList'),

    url(r'^fleet/add/service-booking/(?P<vehicle_id>\-{0,1}\d+$)', views.bookservice, name='bookservice'),
    url(r'^fleet/edit/service-booking/(?P<trans_id>\-{0,1}\d+$)', views.editbookservice, name='editbookservice'),
    url(r'^fleet/view/service-booking/(?P<trans_id>\-{0,1}\d+$)', views.viewbookservice, name='viewbookservice'),
    url(r'^fleet/view/service-bookings-list/$', views.servicebookingsList, name='servicebookingsList'),

    url(r'^fleet/add/traffic-fine/(?P<vehicle_id>\-{0,1}\d+$)', views.trafficfines, name='trafficfines'),
    url(r'^fleet/edit/traffic-fine/(?P<trans_id>\-{0,1}\d+$)', views.edittrafficfines, name='edittrafficfines'),
    url(r'^fleet/view/traffic-fine/(?P<trans_id>\-{0,1}\d+$)', views.viewtrafficfines, name='viewtrafficfines'),
    url(r'^fleet/view/traffic-fines-list/$', views.trafficfinesList, name='trafficfinesList'),

    url(r'^fleet/add/vehicle-inspection/(?P<vehicle_id>\-{0,1}\d+$)', views.mileagelog, name='mileagelog'),
    url(r'^fleet/edit/vehicle-inspection/(?P<trans_id>\-{0,1}\d+$)', views.editmileagelog, name='editmileagelog'),
    url(r'^fleet/view/vehicle-inspection/(?P<trans_id>\-{0,1}\d+$)', views.viewmileagelog, name='viewmileagelog'),
    url(r'^fleet/view/vehicle-inspections-list/$', views.mileagelogList, name='mileagelogList'),

    url(r'^fleet/add/vehicle-maintenance/(?P<vehicle_id>\-{0,1}\d+$)', views.vehiclemaintenance, name='vehiclemaintenance'),
    url(r'^fleet/edit/vehicle-maintenance/(?P<trans_id>\-{0,1}\d+$)', views.editvehiclemaintenance, name='editvehiclemaintenance'),
    url(r'^fleet/view/vehicle-maintenance/(?P<trans_id>\-{0,1}\d+$)', views.viewvehiclemaintenance, name='viewvehiclemaintenance'),
    url(r'^fleet/view/vehicle-maintenance-list/$', views.vehiclemaintenanceList, name='vehiclemaintenanceList'),
   
    url(r'^fleet/requisition/vehicle/maintenance/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':VehicleMaintenance}, name='requisition_vehiclemaintenance'),
    url(r'^fleet/requisition/vehicle/insurance/excess/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':InsuranceClaim}, name='requisition_insuranceclaimexcess'),    
    url(r'^fleet/requisition/vehicle/licencing/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':RenewLicenceDisk}, name='requisition_vehiclelicencing'),
    url(r'^fleet/requisition/vehicle/fuel/allocation/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':FuelAllocation}, name='requisition_vehiclefuelallocation'),
    url(r'^fleet/requisition/vehicle/fuel/transfer/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':FuelTransfer}, name='requisition_vehiclefueltransfer'),
    url(r'^fleet/requisition/vehicle/trafficfine/(?P<obj_id>\-{0,1}\d+$)', views.requisition, {'obj_type':VehicleMaintenance}, name='requisition_vehicletrafficfine'),

    url(r'^fleet/requisition/item/(?P<obj_id>\-{0,1}\d+$)', views.requisition_item, name='requisition_item'),
    url(r'^fleet/view/requisition/(?P<obj_id>\-{0,1}\d+$)', views.view_requisition, name='view_requisition'),
   
    url(r'^fleet/add/licence-disk-renewal/(?P<vehicle_id>\-{0,1}\d+$)', views.renewlicencedisk, name='renewlicencedisk'),
    url(r'^fleet/edit/licence-disk-renewal/(?P<trans_id>\-{0,1}\d+$)', views.editrenewlicencedisk, name='editrenewlicencedisk'),
    url(r'^fleet/view/licence-disk-renewal/(?P<trans_id>\-{0,1}\d+$)', views.viewrenewlicencedisk, name='viewrenewlicencedisk'),
    url(r'^fleet/view/licence-disk-renewals-list/$', views.licenceDiskRenewalList, name='licenceDiskRenewalList'),
    
    url(r'^fleet/add/vehicle-incident/(?P<vehicle_id>\-{0,1}\d+$)', views.vehicleincidences, name='vehicleincidences'),
    url(r'^fleet/edit/vehicle-incident/(?P<trans_id>\-{0,1}\d+$)', views.editvehicleincidences, name='editvehicleincidences'),
    url(r'^fleet/view/vehicle-incident/(?P<trans_id>\-{0,1}\d+$)', views.viewvehicleincidences, name='viewvehicleincidences'),
    url(r'^fleet/view/vehicle-incidences-list/$', views.incidencesList, name='incidencesList'),

    url(r'^fleet/add/vehicle-claim/(?P<vehicle_id>\-{0,1}\d+$)', views.addVehicleClaim, name='addVehicleClaim'),
    url(r'^fleet/view/vehicle-claim(?P<trans_id>\-{0,1}\d+$)', views.editVehicleClaim, name='viewVehicleClaim'),
    url(r'^fleet/edit/vehicle-claim(?P<trans_id>\-{0,1}\d+$)', views.viewVehicleClaim, name='editVehicleClaim'),   
    url(r'^fleet/view/vehicle-claims-list/$', views.vehicleClaimsList, name='vehicleClaimsList'), 

    url(r'^fleet/fuelcard/$', views.fuelcard, name='fuelcard'), 
    url(r'^fleet/allocate/fuel/(?P<vehicle_id>\-{0,1}\d+$)', views.allocatefuel, name='allocatefuel'),
    url(r'^fleet/edit/allocate/fuel/(?P<trans_id>\-{0,1}\d+$)', views.editallocatefuel, name='editallocatefuel'),

    url(r'^fleet/fueltransfer/$', views.fuelTransfer, name='fuel_transfer'), 

    url(r'^fleet/tripLog/Imports/(?P<vehicle_id>\-{0,1}\d+$)', views.tripLogImports, name='tripLogImports'),
    url(r'^fleet/loadtriplog/(?P<trip_id>\-{0,1}\d+$)', views.load_trip_log, name='load_trip_log'),

    url(r'^fleet/page_carousel/$', views.page_carousel, name='page_carousel'),  
    url(r'^fleet/get_fuel_card/$', views.get_fuel_card, name='get_fuel_card'),
    url(r'^fleet/get_employee/$', views.get_employee, name='get_employee'), 
    url(r'^fleet/get_vehicle/$', views.get_vehicle, name='get_vehicle'),
    url(r'^fleet/get_region/$', views.get_region, name='get_region'),

    url(r'^fleet/reports/current_drivers/$', views.rpt_current_drivers, name='rpt_current_drivers'), 
    url(r'^fleet/reports/vehicle_allocations/$', views.rpt_vehicle_allocations, name='rpt_vehicle_allocations'), 
    url(r'^fleet/reports/vehicle_fuel_allocations/$', views.rpt_vehicle_fuel_allocations, name='rpt_vehicle_fuel_allocations'), 
    url(r'^fleet/reports/vehicle_mileages/$', views.rpt_vehicle_mileages, name='rpt_vehicle_mileages'), 
    url(r'^fleet/reports/mileage_aggregates/$', views.rpt_mileage_aggregates, name='rpt_mileage_aggregates'), 
    url(r'^fleet/reports/driver_mileages/$', views.rpt_driver_mileages, name='rpt_driver_mileages'),
    url(r'^fleet/reports/driver_vehicle_allocations/$', views.rpt_driver_vehicle_allocations, name='rpt_driver_vehicle_allocations'),
    url(r'^fleet/reports/driver_fuel_allocations/$', views.rpt_driver_fuel_allocations, name='rpt_driver_fuel_allocations'),
    url(r'^fleet/reports/service_due/$', views.rpt_service_due, name='rpt_service_due'),
    url(r'^fleet/reports/service_overdue/$', views.rpt_service_overdue, name='rpt_service_overdue'),
    url(r'^fleet/reports/licence_disks_due/$', views.rpt_licence_disks_due, name='rpt_licence_disks_due'),
    url(r'^fleet/reports/licence_disks_expired/$', views.rpt_licence_disks_expired, name='rpt_licence_disks_expired'),
    url(r'^fleet/reports/vehicle_traffic_fines/$', views.rpt_vehicle_traffic_fines, name='rpt_vehicle_traffic_fines'),
    url(r'^fleet/reports/driver_traffic_fines/$', views.rpt_driver_traffic_fines, name='rpt_driver_traffic_fines'),    
    url(r'^fleet/reports/vehicle_maintenance/$', views.rpt_vehicle_maintenance, name='rpt_vehicle_maintenance'),
    url(r'^fleet/reports/vehicle_insurance_claims/$', views.rpt_vehicle_insurance_claims, name='rpt_vehicle_insurance_claims'),
    url(r'^fleet/reports/vehicle_incidences/$', views.rpt_vehicle_incidences, name='rpt_vehicle_incidences'),
    url(r'^fleet/reports/driver_incidences/$', views.rpt_driver_incidences, name='rpt_driver_incidences'),

    
    url(r'^fleet/authorizations/$', views.authorizations, name='authorizations'),
    url(r'^fleet/comments/$', views.comments, name='comments'),

        
    url(r'^fleet/redirect_from_comment/$', views.redirect_from_comment, name='redirect_from_comment'),    
]

operations/home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^dashboard/$', views.dash, name='dash'),
]

operations/operations/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from django_js_reverse.views import urls_js
from models import RegionAutoComplete,DistrictAutoComplete

urlpatterns = [
    url(r'^region_autocomplete/$', RegionAutoComplete.as_view(), name='region_autocomplete'),
    url(r'^district_autocomplete/$', DistrictAutoComplete.as_view(), name='district_autocomplete'),    
    url(r'^$', views.home, name='home'),
    url(r'^jsreverse/$', urls_js, name='js_reverse'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout,{'next_page':'/'}, name='logout'),

    url(r'^about/$', views.about, name='about'),
    url(r'^users$', views.users, name='users'),
    url(r'^users/fleet-admins/(?P<fleet_administrators>\d+)/$', views.users, name='fleet_admins'),
    url(r'^user/add/$', views.user_edit, name='user_add'),
    url(r'^user/edit/(?P<user_id>\d+)/$', views.user_edit, name='user_edit'),
    
    
    url(r'^', include('fleet_management.urls', namespace='fleetmanagement')),
    url(r'^', include('employees.urls', namespace='employees')), 
    url(r'^', include('facilities.urls', namespace='facilities')),   
    url(r'^', include('assets.urls', namespace='assets')),
    url(r'^', include('api.urls', namespace='api')),

    url(r'^regions$', views.view_regions, name='view_regions'),
    url(r'^branches$', views.view_branches, name='view_branches'),

    url(r'^downloads/$', views.downloads_list, name="view_downloads"),
    url(r'^downloads/(?P<file_id>\d+)/$', views.file_download_task, name="file_download"),

    url(r'^tickets$', views.view_tickets, name='view_tickets'),
    url(r'^tickets/add$', views.edit_ticket, name='add_ticket'),
    url(r'^tickets/edit(?P<ticket_id>\d+)/$', views.edit_ticket, name='edit_ticket'),

    url(r'^service_provider/uploads$', views.service_provider_uploads, name='service_provider_uploads'),
    url(r'^districts/uploads$', views.district_uploads, name='district_uploads'),

    url(r'^accounts/user_profile/(?P<user_id>\-{0,1}\d+$)', views.user_profile, name='user_profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

operations/home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class SignUp(models.Model):
    email = models.EmailField()
    full_name = models.CharField(max_length=120, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
    	return self.email

operations/home/forms.py
from django import forms
from .models import SignUp

class SignUpForm(forms.ModelForm):
	class Meta:
		model = SignUp
		fields = ['full_name', 'email']

	def clean_email(self):
		email = self.cleaned_data.get('email')
		email_base, provider = email.split("@")
		domain, extension = provider.split('.')
		if not domain == 'emeraldlife.co':
			raise forms.ValidationError("Please use your valid Emerald Life email")
		if not extension == "za":
			raise forms.ValidationError("Please a valid Emerald Life email address")		
		return email

	def clean_full_name(self):
		full_name = self.cleaned_data.get('full_name')
		return full_name



class ContactForm(forms.Form):
	full_name = forms.CharField()
	email = forms.EmailField()
	message = forms.CharField()

operations/templates/_css.html
{% load staticfiles %}


<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">  

<link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">     

<link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">

<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">

<link href="{% static 'css/all.css' %}" rel="stylesheet">

<link href="{% static 'css/bootstrap-submenu.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet"> 

<link href="{% static 'css/custom.css' %}" rel="stylesheet">
<link href="{% static 'css/base.css' %}" rel="stylesheet"> 

<link href="{% static 'css/metisMenu.min.css' %}" rel="stylesheet"> 

<link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

<link href="{% static 'css/morris.css' %}" rel="stylesheet"> 

<link href="{% static 'css/vehicle_panel.css' %}" rel="stylesheet">
<link href="{% static 'css/vehicle.css' %}" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="{% static 'autocomplete_light/vendor/select2/dist/css/select2.css' %}" />

<link href="{% static 'css/panel.css' %}" rel="stylesheet">

<link href="{% static 'css/bootstrap-multiselect.css' %}" rel="stylesheet">

operations/templates/_scripts.html
{% load staticfiles %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

<script type="text/javascript" src="{% static 'autocomplete_light/jquery.init.js' %}"></script>
<script type="text/javascript" src="{% static 'autocomplete_light/autocomplete.init.js' %}"></script>    
<script type="text/javascript" src="{% static 'autocomplete_light/select2.js' %}"></script>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'js/bootstrap-multiselect.min.js' %}"></script>

<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/morris.min.js' %}"></script>
<script src="{% static 'js/raphael.min.js' %}"></script>
<script src="{% static 'js/select2.min.js' %}"></script>
<script src="{% static 'js/bootstrap-submenu.min.js' %}"></script>
<script src="{% static 'js/dj-reverse.js' %}"></script>

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

<script>
$(function() {
  $('a[data-toggle="pill"]').on('shown.bs.tab', function (e) {
    localStorage.setItem('lastTab', $(this).attr('href'));
  });
  var lastTab = localStorage.getItem('lastTab');
  if (lastTab) {
    $('[href="' + lastTab + '"]').tab('show');
  }
});
</script>

<script src="{% static 'js/vehicle_panel.js' %}"></script>

operations/templates/loading.html
{% load staticfiles%}
<div class="load_spinner">	
 <img id="id_loading" src="{% static 'img/busy.gif' %}"/>	
</div>

operations/templates/submenu.html
 {% load staticfiles %}
 {% block javascript %}
  
    <script>
      $(function() {
        $(".auto-complete-vehicle").autocomplete({
        source: "{% url 'fleet:get_vehicle' %}",
          minLength: 2});

        $(".auto-complete-driver").autocomplete({
        source: "{% url 'fleet:get_employee' %}",
          minLength: 2});

        $('[data-submenu]').submenupicker();


      });

  </script>
  

{% endblock %}

<h4>With button</h4>
<div class="row">
  <div class="col-sm-4 col-sm-offset-2 m-b">
    <div class="dropdown">
      <a class="dropdown-toggle" type="button" data-toggle="dropdown" data-submenu>
        Reports <span class="caret"></span>
      </a>

      <ul class="dropdown-menu">
  <li class="dropdown-header">Elopsys Reporting</li>
  <li class="divider"></li>
  <li class="dropdown-submenu">
    <a tabindex="0">Fleet</a>
    <ul class="dropdown-menu"> 
      <li class="dropdown-header">Fleet Reports</li> 
      <li class="divider"></li>   
      <li class="dropdown-submenu">
        <a tabindex="0">Vehicle</a>

        <ul class="dropdown-menu">
          <li class="dropdown-header">Vehicle Reports</li>
          <li class="divider"></li>   
          <li><a tabindex="0" href="{% url 'fleet:rpt_current_drivers' %}">Current Drivers Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_vehicle_allocations' %}">Vehicle Allocations Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_vehicle_fuel_allocations' %}">Vehicle Fuel Allocations Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_vehicle_mileages' %}">Vehicle Mileage Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_mileage_aggregates' %}">Vehicle Mileage Agregates Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_service_due' %}">Vehicle Service Due Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_service_overdue' %}">Vehicle Service Overdue Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_licence_disks_due' %}">Vehicle Licencing Due Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_licence_disks_expired' %}">Vehicle Licencing Expired Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_vehicle_traffic_fines' %}">Vehicle Traffic Fines Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_vehicle_maintenance' %}">Vehicle Maintenance Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_vehicle_insurance_claims' %}">Vehicle Insurance Claims Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_vehicle_incidences' %}">Vehicle Incidences Report</a></li>
        </ul>
      </li>      
      <li class="dropdown-submenu">
        <a tabindex="0">Driver</a>

        <ul class="dropdown-menu">
          <li class="dropdown-header">Driver Reports</li>
          <li class="divider"></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_driver_vehicle_allocations' %}">Driver Vehicle Allocations Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_driver_fuel_allocations' %}">Driver Fuel Allocations Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_driver_mileages' %}">Driver Mileages Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_driver_traffic_fines' %}">Driver Traffic Fines Report</a></li>
          <li><a tabindex="0" href="{% url 'fleet:rpt_driver_incidences' %}">Driver Incidences Report</a></li>         
        </ul>
      </li>
    </ul>
</li>
<li><a tabindex="0">Assets</a></li>
<li><a tabindex="0">Offices</a></li>
<li><a tabindex="0">Inventory</a></li>
</ul>

    </div>
  </div>
  
</div>