operations/api/urls.py
from django.conf.urls import include, url
from django.conf import settings
import views


urlpatterns = [
    url(r'^/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^get_vehicle_info/', views.get_vehicle_info),
    url(r'^push_agent_data/', views.push_agent_data),
    url(r'^push_region_data/', views.push_region_data),
    url(r'^push_branch_data/', views.push_branch_data),
]

operations/facilities/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from dal import autocomplete

import views
from fleet_management.autocomplete import *

from .models import *
from employees.models import *
from operations.models import *
from facilities.models import *

urlpatterns = [
    url(r'^stock_items/$', views.stock_items, name='stock_items'),
    url(r'^stock_items/edit/(?P<item_id>\d+)/$', views.edit_stock_item, name='edit_stock_item'),
    url(r'^stock_items/add/$', views.edit_stock_item, name='add_stock_item'),    
    
    url(r'^get_opening_balance/(?P<item_id>\d+)/$', views.get_opening_balance, name='get_opening_balance'),

    url(r'^stock_items/uploads/$', views.stock_items_uploads, name='stock_items_uploads'),

    url(r'^stock_items/transactions/$', views.stock_items_transactions, name='stock_items_transactions'),
    url(r'^stock_items/transactions/edit/(?P<item_id>\d+)/$', views.edit_stock_item_transaction, name='edit_stock_item_transaction'),
    url(r'^stock_items/transactions/add/$', views.edit_stock_item_transaction, name='add_stock_item_transaction'),

    url(r'^stock_item_delete/(?P<item_id>\d+)/$', views.stock_item_delete, name='stock_item_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

operations/operations/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from django_js_reverse.views import urls_js
from models import RegionAutoComplete,DistrictAutoComplete

urlpatterns = [
    url(r'^region_autocomplete/$', RegionAutoComplete.as_view(), name='region_autocomplete'),
    url(r'^district_autocomplete/$', DistrictAutoComplete.as_view(), name='district_autocomplete'),    
    url(r'^$', views.home, name='home'),
    url(r'^jsreverse/$', urls_js, name='js_reverse'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout,{'next_page':'/'}, name='logout'),

    url(r'^about/$', views.about, name='about'),
    url(r'^users$', views.users, name='users'),
    url(r'^users/fleet-admins/(?P<fleet_administrators>\d+)/$', views.users, name='fleet_admins'),
    url(r'^user/add/$', views.user_edit, name='user_add'),
    url(r'^user/edit/(?P<user_id>\d+)/$', views.user_edit, name='user_edit'),
    
    
    url(r'^', include('fleet_management.urls', namespace='fleetmanagement')),
    url(r'^', include('employees.urls', namespace='employees')), 
    url(r'^', include('facilities.urls', namespace='facilities')),   
    url(r'^', include('assets.urls', namespace='assets')),
    url(r'^', include('api.urls', namespace='api')),

    url(r'^regions$', views.view_regions, name='view_regions'),
    url(r'^branches$', views.view_branches, name='view_branches'),

    url(r'^downloads/$', views.downloads_list, name="view_downloads"),
    url(r'^downloads/(?P<file_id>\d+)/$', views.file_download_task, name="file_download"),

    url(r'^tickets$', views.view_tickets, name='view_tickets'),
    url(r'^tickets/add$', views.edit_ticket, name='add_ticket'),
    url(r'^tickets/edit(?P<ticket_id>\d+)/$', views.edit_ticket, name='edit_ticket'),

    url(r'^service_provider/uploads$', views.service_provider_uploads, name='service_provider_uploads'),
    url(r'^districts/uploads$', views.district_uploads, name='district_uploads'),

    url(r'^accounts/user_profile/(?P<user_id>\-{0,1}\d+$)', views.user_profile, name='user_profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

operations/facilities/models.py
from django.db import models
from lib.models import BaseModel
from lib.fields import ProtectedForeignKey
from django.core.validators import MaxValueValidator, MinValueValidator
from simple_history.models import HistoricalRecords
from datetime import datetime
from django.db.models import Sum

class StockItem(BaseModel):
	STOCK_CATEGORIES = (('consumables', 'Consumables'),
						('sanitary', 'Sanitary'),
						('stationery', 'Stationery'))
	item_name = models.CharField(max_length=255, unique=True, null=False, blank=False, verbose_name="Item Name")
	category = models.CharField(max_length=255, null=False, blank=False, choices=STOCK_CATEGORIES)
	stock_quantity = models.IntegerField(null=True, blank=True, verbose_name='Stock Quantity',
										validators=[MinValueValidator(0)])
	created_by = ProtectedForeignKey('operations.OperationsUser', null=False, blank=False, related_name='created_stock_item')
	modified_by = ProtectedForeignKey('operations.OperationsUser', null=True, blank=True, related_name='modified_stock_item')
	
	def __unicode__(self):
		return self.item_name


class StockTransaction(BaseModel):
	STOCK_TRANSACTION_TYPES = (('allocated','Allocated'),
							   ('received','Received'))

	stock_item = ProtectedForeignKey('StockItem', null=True, blank=True, related_name="stock_item_stock_recieved", verbose_name='Stock Item')
	reference = models.CharField(max_length=255, null=False, blank=False)
	transaction_type = models.CharField(max_length=255, null=False, blank=False, choices=STOCK_TRANSACTION_TYPES)
	opening_stock = models.IntegerField(null=True, blank=True, verbose_name='Opening Stock',
										validators=[MinValueValidator(0)])
	quantity = models.IntegerField(null=True, blank=True, verbose_name='Quantity',
										validators=[MinValueValidator(0)])
	transaction_date = models.DateTimeField(null=True, blank=True, verbose_name='Transaction Date')
	supplier = ProtectedForeignKey('operations.Vendor', null = True, blank = True, related_name='supplier_stock_received')
	district = ProtectedForeignKey('operations.Branch', null = True, blank = True, related_name='district_stock_allocation')
	comment = models.TextField(null=True, blank=True)
	created_by = ProtectedForeignKey('operations.OperationsUser', null=False, blank=False, related_name='created_stock_received')
	modified_by = ProtectedForeignKey('operations.OperationsUser', null=True, blank=True, related_name='modified_stock_received')
	
	@property
	def stock_balance(self):
		if self.transaction_type == 'allocated':
			stock_bal = self.opening_stock - self.quantity
		else:
			stock_bal = self.opening_stock + self.quantity
		return stock_bal

operations/facilities/views.py
import os

from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.db.models import Count, Sum, Q
from django.db.models.functions import Concat
from django.db.models import Value as V
import json
from employees.models import *
from facilities.models import *
from fleet_management.exporter import *
from fleet_management.importer import *
import threading
import re

from forms import StockItemForm, StockTransactionForm, StockItemImportForm
from forms import StockFilterForm, StockTransactionFilterForm

@login_required
@csrf_exempt
def get_opening_balance(request, item_id):
    stock_item = StockItem.objects.get(id=item_id)
   
    item = {}
    item['id'] = stock_item.id
    item['label'] = stock_item.item_name
    item['value'] = stock_item.stock_quantity or 0

    results = json.dumps(item)
    mimetype = 'application/json'
    return HttpResponse(results, mimetype)

@login_required
def stock_items_uploads(request, template="facilities/stock_uploads.html"):
    context = {}

    form = StockItemImportForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        import_stock_items_data(request.user, form.cleaned_data.get('stock_item_file'))

    context['form'] = form

    return render(request, template, context)

@login_required
def stock_items(request, template="facilities/stock_items.html"):
    context = {}
       
    stock_items = StockItem.objects.all() 
    stock_filter_form = StockFilterForm(request.GET or None)
    heading = "Stock Items"
    
    if u'filter' in request.GET or u'extract' in request.GET:
        if stock_filter_form.is_valid():
            stock_items = stock_filter_form.filter(stock_items)            

    if u'extract' in request.GET:
        download_thread = threading.Thread(target=extract_stock_items_data, 
                                           args=(request.user, 'all_stock_items', stock_items, 
                                                 stock_filter_form.cleaned_data))
        download_thread.start()
        messages.success(request, 'Your extract has been added to the download queue. Queue processing may take a while. Check your report in downloads.')

    context['stock_items'] = stock_items
    context['stock_filter_form'] = stock_filter_form
    context['heading'] = heading
    return render(request, template, context)


@login_required
def stock_items_transactions(request, template="facilities/stock_items_transactions.html"):
    context = {}
       
    stock_items = StockTransaction.objects.all() 
    stock_filter_form = StockTransactionFilterForm(request.GET or None)
    heading = "Stock Items Transactions"
    
    if u'filter' in request.GET or u'extract' in request.GET:
        if stock_filter_form.is_valid():
            stock_items = stock_filter_form.filter(stock_items)

    if u'extract' in request.GET:
        download_thread = threading.Thread(target=extract_stock_items_received_data, 
                                           args=(request.user, 'all_stock_items', stock_items, 
                                                 stock_filter_form.cleaned_data))
        download_thread.start()
        messages.success(request, 'Your extract has been added to the download queue. Queue processing may take a while. Check your report in downloads.')
            
    context['stock_items'] = stock_items
    context['stock_filter_form'] = stock_filter_form
    context['heading'] = heading
    return render(request, template, context)

@login_required
def edit_stock_item(request, item_id=None, template="facilities/stock_item_edit.html", context=None):

    context = context or {}

    stock_item = StockItem.objects.get(pk=item_id) if item_id else None
    
    stock_item_form = StockItemForm(request.POST or None, instance=stock_item)

    if u'save' in request.POST:
        if stock_item_form.is_valid():
            stock_item = stock_item_form.save(request.user)
            stock_item.save()
            
            next = request.POST.get('next', '/')
            
            return HttpResponseRedirect(next)

    if u'cancel' in request.POST:
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)

    context['stock_item'] = stock_item
    context['stock_item_form'] = stock_item_form
    
    return render(request, template, context)


@login_required
def edit_stock_item_transaction(request, item_id=None, template="facilities/stock_item_transaction_edit.html", context=None):

    context = context or {}
    quantity = 0
    has_intsance = False
    opening_balance = 0
    stock_item = StockTransaction.objects.get(pk=item_id) if item_id else None
    if stock_item:
        quantity = stock_item.quantity
        opening_balance = stock_item.opening_stock
        transaction = stock_item.transaction_type
        stk = stock_item.stock_item
        has_intsance = True
       
    stock_item_form = StockTransactionForm(request.POST or None, instance=stock_item)
        
    if u'save' in request.POST:
        if stock_item_form.is_valid():
            stock_item = stock_item_form.save(commit=False)
            stock_item.modified_by = request.user
            stock_item.created_by = request.user
            if has_intsance:
                stock_item.opening_stock = opening_balance
                stock_item.stock_item = stk
                stock_item.transaction_type = transaction
            else:
                stock_item.opening_stock = stock_item.stock_item.stock_quantity or 0
            stock_item.save() 

            stock = stock_item.stock_item
            if not has_intsance:
                stock.stock_quantity = stock_item.stock_balance
                stock.modified_by_id = request.user
            else:
                if transaction == 'allocated':
                    stock.stock_quantity -= stock_item.quantity - quantity
                    stock.modified_by_id = request.user
                else:
                    stock.stock_quantity += stock_item.quantity - quantity
                    stock.modified_by_id = request.user
            stock.save()
            
            next = request.POST.get('next', '/')
            if 'edit' in next or 'add' in next:
                return redirect(reverse('facilities:stock_items_transactions'))
            return HttpResponseRedirect(next)
        

    if u'cancel' in request.POST:
        next = request.POST.get('next', '/')
        if 'edit' in next or 'add' in next:
            return redirect(reverse('facilities:stock_items_transactions'))
        return HttpResponseRedirect(next)

    context['stock_item'] = stock_item
    context['stock_item_form'] = stock_item_form
    
    return render(request, template, context)

@login_required
def stock_item_delete(request, item_id):

    stock_item = StockItem.objects.get(pk=item_id)
    stock_item.deleted = True
    stock_item.save()

    return redirect(reverse('facilities:stock_items'))

operations/templates/facilities/stock_item_edit.html
{% extends "base.html" %}
{% load staticfiles %}

{% load bootstrap4 %}
{% load humanize %}
{% block javascript %}

<!-- <script src="{% static 'js/fuel_cards.js' %}"></script> -->

{% endblock %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    {% if stock_item %}
    <b>Edit Stock Item</b>
    {% else %}
    <b>Add Stock Item:</b>
    {% endif %}
  </div>
  
  <div class="panel-body">
    
    <form method="POST" class="form-2" novalidate enctype="multipart/form-data">      
      <input type="hidden" name="next" value="{{ request.META.HTTP_REFERER }}">
      {% csrf_token %}
      
      <div id="edit_stock_item_tab_content" class="tab-content">
        <div class="tab-pane fade active in" id="details">
          <br>
          <div class='col-md-6'>
            {% bootstrap_field stock_item_form.item_name %}
          </div>
          <div class='col-md-6'>
            {% bootstrap_field stock_item_form.category %}
          </div>

      </div>

      <div class="btn-group-horizontal col-lg-12">
        <div class='pull-right'>
          <button type="submit" name="save" class="btn btn-primary">
            <i class='fa fa-floppy-o'></i> Save
          </button> 
          <button type="submit" name="cancel" class="btn btn-primary">
            <i class='fa fa-undo'></i> Cancel
          </button>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

operations/templates/facilities/stock_item_transaction_edit.html
{% extends "base.html" %}
{% load staticfiles %}

{% load bootstrap4 %}
{% load humanize %}
{% block javascript %}

<script src="{% static 'js/stock_items.js' %}"></script>

{% endblock %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    {% if stock_item %}
    <b>Edit Stock Item Transaction</b>
    {% else %}
    <b>Add Stock Item Transaction:</b>
    {% endif %}
  </div>
  
  <div class="panel-body">
    
    <form method="POST" class="form-2" novalidate enctype="multipart/form-data">      
      <input type="hidden" name="next" value="{{ request.META.HTTP_REFERER }}">
      <input type="hidden" name="stock_item" value="{{stock_item_form.stock_item.value}}" />
      <input type="hidden" name="opening_stock" value="{{stock_item_form.opening_stock.value}}" />
      <input type="hidden" name="transaction_type" value="{{stock_item_form.transaction_type.value}}" />
      {% csrf_token %}
      
      <div id="edit_stock_item_tab_content" class="tab-content">
        <div class="tab-pane fade active in" id="details">
          <br>
          <div class='col-md-6'>
            {% bootstrap_field stock_item_form.stock_item %}
            {% bootstrap_field stock_item_form.transaction_type %} 
            <div id="reference">{% bootstrap_field stock_item_form.reference %}</div>            
            {% bootstrap_field stock_item_form.transaction_date %}            
            {% bootstrap_field stock_item_form.opening_stock%}
            {% bootstrap_field stock_item_form.quantity %}   
          </div>
          <div class='col-md-6'>
            <div id="supplier">{% bootstrap_field stock_item_form.supplier %}</div>
            <div id="district">{% bootstrap_field stock_item_form.district %}</div>
            {% bootstrap_field stock_item_form.comment %}          
          </div>

      </div>

      <div class="btn-group-horizontal col-lg-12">
        <div class='pull-right'>
          <button type="submit" name="save" class="btn btn-primary">
            <i class='fa fa-floppy-o'></i> Save
          </button> 
          <button type="submit" name="cancel" class="btn btn-primary">
            <i class='fa fa-undo'></i> Cancel
          </button>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

operations/templates/facilities/stock_items.html
{% extends "base.html" %}
{% load staticfiles%}
{% load bootstrap4 %}
{% load humanize %}
{% block javascript %}
    <script src="{% static 'js/stock_items.js' %}"></script>
{% endblock %}
{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>{{heading}}</b>
    
  </div> 
  <div class="panel-body">

    <form id="stock_items_filter_form" method="GET">
        {% csrf_token %}

    <div class="row">
        <input name="filter" type="hidden">
        
        <div class='col-lg-4 pull-right'>
          <div class='pull-right'>
            <button type="submit" name="search" class="btn btn-primary" title="Search"><i class="fa fa-search"></i> Search</button>
            <a href="{% url 'facilities:stock_items' %}"  class="btn btn-primary" title="Clear Search"><i class="fa fa-search-minus"></i> Clear</a>
            <button type="submit" id="load_modal" class="btn btn-primary" title="Extract Stock Items"><i class="fa fa-download"></i> Extract</button>
            {% if user.is_superuser %}
            <a href="{% url 'facilities:stock_items_uploads' %}" class="btn btn-primary" title="Import Stock Items"><i class="fa fa-upload"></i> Import</a>
            <a href="{% url 'facilities:add_stock_item' %}" class="btn btn-primary" title="Add Stock Item"><i class="fa fa-plus"></i> Add</a>
            {% endif %}
          </div>
        </div>
        
      <div class='col-lg-8'>
        {% for field in stock_filter_form %}
          <div class='col-lg-3'>
            {% bootstrap_field field layout='inline' %}
          </div>
          {% endfor %}
      </div>
    </div>
    
    <div class="tab-content">
      <div id="fuel_card" class="tab-pane fade in active">
        {% include 'facilities/widgets/_stock_items_list.html' %}

      </div>
    </div>

    <div class="modal fade" id="extract_modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modalLabel"><i class="fa fa-info-circle" aria-hidden="true"></i> Extract Stock Item(s)</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <b> Are you sure you want to download the extract</b>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="submit" name="extract" id="extract" class="btn btn-primary">Ok</button>
            </div>
          </div>
        </div>
    </div>

    <div class="modal fade" id="stock_item_delete_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Are you sure you want to delete this item?</p>
            </div>
            <div class="modal-footer">
              <button type="cancel" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <a href="#" type="submit" class="btn btn-primary">Delete</a>
            </div>     
          </div>
        </div>
    </div>
  </form>
  </div>
</div>
{% endblock %}

operations/templates/facilities/stock_items_transactions.html
{% extends "base.html" %}
{% load staticfiles%}
{% load bootstrap4 %}
{% load humanize %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>{{heading}}</b>
    
  </div> 
  <div class="panel-body">

    <form id="stock_items_filter_form" method="GET">
        {% csrf_token %}

    <div class="row">     
        <input name="filter" type="hidden">
        
        <div class='col-lg-4 pull-right'>
          <div class='pull-right'>
            <button type="submit" name="search" class="btn btn-primary" title="Search"><i class="fa fa-search"></i> Search</button>
            <a href="{% url 'facilities:stock_items_transactions' %}"  class="btn btn-primary" title="Clear Search"><i class="fa fa-search-minus"></i> Clear</a>
            <button type="submit" id="load_modal" class="btn btn-primary" title="Extract Stock Received"><i class="fa fa-download"></i> Extract</button>
            {% if user.is_superuser %}         
            <a href="{% url 'facilities:add_stock_item_transaction' %}" class="btn btn-primary" title="Add Stock Received"><i class="fa fa-plus"></i> Add</a>
            {% endif %}
          </div>
        </div>
        
      <div class='col-lg-8'>
        {% for field in stock_filter_form %}
          <div class='col-lg-3'>
            {% bootstrap_field field layout='inline' %}
          </div>
          {% endfor %}      
      </div>       
    </div>
    
    <div class="tab-content">
      <div id="fuel_card" class="tab-pane fade in active">
        {% include 'facilities/widgets/_stock_items_transactions_list.html' %}

      </div>
    </div>

    <div class="modal fade" id="extract_modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">      
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modalLabel"><i class="fa fa-info-circle" aria-hidden="true"></i> Extract Stock Item(s)</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <b> Are you sure you want to download the extract</b>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="submit" name="extract" id="extract" class="btn btn-primary">Ok</button>
            </div>
          </div>
        </div>     
    </div>
  </form>
  </div>
</div>
{% endblock %}

operations/templates/facilities/stock_uploads.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% load humanize %}

{% block content%}
<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Upload Stock Items</b>
  </div>

  <div class="panel-body">
    <form method='post' enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <br>
      <button class="btn btn-primary pull-right">Upload Stock Items</button>
    </form>
  </div>
</div>
{% endblock %}