operations/api/urls.py
from django.conf.urls import include, url
from django.conf import settings
import views


urlpatterns = [
    url(r'^/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^get_vehicle_info/', views.get_vehicle_info),
    url(r'^push_agent_data/', views.push_agent_data),
    url(r'^push_region_data/', views.push_region_data),
    url(r'^push_branch_data/', views.push_branch_data),
]

operations/employees/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
import views

urlpatterns = [
    url(r'^employees/$', views.employees, name='employees'),
    url(r'^employees/edit/(?P<employee_id>\d+)/$', views.edit_employee, name='edit_employee'),
    url(r'^reports/drivers_licence_expiry$', views.drivers_licence_expiry, name='drivers_licence_expiry'),

]

operations/fleet_management/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from dal import autocomplete

import views
from fleet_management.autocomplete import *

from .models import *
from employees.models import *
from operations.models import *
from facilities.models import *

urlpatterns = [

    url(r'^vehicle-autocomplete/$', VehicleAutocomplete.as_view(model=Vehicle), name='vehicle-autocomplete'),
    url(r'^driver-autocomplete/$', DriverAutocomplete.as_view(model=Employee), name='driver-autocomplete'),
    url(r'^fuel_card-autocomplete/$', FuelCardAutocomplete.as_view(model=FuelCard), name='fuel_card-autocomplete'), 
    url(r'^fuel_card-autocomplete-filtered/(?P<vehicle_id>\d+)/$', FuelCardAutocomplete.as_view(model=FuelCard), name='fuel_card-autocomplete-filtered'),
    url(r'^vendor_tracker-autocomplete/$', VendorTrackerAutocomplete.as_view(model=Vendor), name='vendor_tracker-autocomplete'),
    url(r'^vendor_purchase_detail-autocomplete/$', VendorPurchaseDetailAutocomplete.as_view(model=Vendor), name='vendor_purchase_detail-autocomplete'),
    url(r'^vendor_service_provider-autocomplete/$', VendorServiceMaintenanceAutocomplete.as_view(model=Vendor), name='vendor_service_provider-autocomplete'),
    url(r'^vendor_fuel_card_supplier-autocomplete/$', VendorFuelCardSupplierAutocomplete.as_view(model=Vendor), name='vendor_fuel_card_supplier-autocomplete'),
    url(r'^vendor_insurance-autocomplete/$', VendorInsuranceAutocomplete.as_view(model=Vendor), name='vendor_insurance-autocomplete'), 
    url(r'^stock_item-autocomplete/$', StockItemAutocomplete.as_view(model=StockItem), name='stock_item-autocomplete'),

    url(r'^get_vehicle_models/(?P<make_id>\d+)/$', views.get_vehicle_models, name='get_vehicle_models'),  
    url(r'^get_vehicle_driver/(?P<vehicle_id>\d+)/$', views.get_vehicle_driver, name='get_vehicle_driver'),

    url(r'^get_vehicle_of_driver/(?P<driver_id>\d+)/$', views.get_vehicle_of_driver, name='get_vehicle_of_driver'),
    url(r'^get_vehicle_details/(?P<vehicle_id>\d+)/$', views.get_vehicle_details, name='get_vehicle_details'),
    url(r'^get_vehicle_division/(?P<vehicle_id>\d+)/$', views.get_vehicle_division, name='get_vehicle_division'),
    url(r'^get_vehicle_region/(?P<vehicle_id>\d+)/$', views.get_vehicle_region, name='get_vehicle_region'),
    url(r'^get_vehicle_district/(?P<vehicle_id>\d+)/$', views.get_vehicle_district, name='get_vehicle_district'),
    url(r'^get_vehicle_ownership/(?P<vehicle_id>\d+)/$', views.get_vehicle_ownership, name='get_vehicle_ownership'),

    url(r'^get_vehicle_vin_number/(?P<vehicle_id>\d+)/$', views.get_vehicle_vin_number, name='get_vehicle_vin_number'),
    url(r'^get_vehicle_engine_number/(?P<vehicle_id>\d+)/$', views.get_vehicle_engine_number, name='get_vehicle_engine_number'),
    url(r'^get_vehicle_colour/(?P<vehicle_id>\d+)/$', views.get_vehicle_colour, name='get_vehicle_colour'),
    url(r'^get_vehicle_make/(?P<vehicle_id>\d+)/$', views.get_vehicle_make, name='get_vehicle_make'),
    url(r'^get_vehicle_model/(?P<vehicle_id>\d+)/$', views.get_vehicle_model, name='get_vehicle_model'),
    url(r'^get_vehicle_year_model/(?P<vehicle_id>\d+)/$', views.get_vehicle_year_model, name='get_vehicle_year_model'),

    url(r'^get_vehicle_fuel_card/(?P<fuel_card_id>\d+)/$', views.get_vehicle_fuel_card, name='get_vehicle_fuel_card'),
    url(r'^get_current_vehicle_driver/(?P<vehicle_id>\d+)/$', views.get_current_vehicle_driver, name='get_current_vehicle_driver'),
    url(r'^get_districts/(?P<region_id>\d+)/$', views.get_districts, name='get_districts'),

    
    url(r'^get_driver_licence/(?P<vehicle_id>\d+)/$', views.get_driver_licence, name='get_driver_licence'),
    url(r'^get_driver_licence_expiry_date/(?P<vehicle_id>\d+)/$', views.get_driver_licence_expiry_date, name='get_driver_licence_expiry_date'),
    
    url(r'^get_service_booking_balances/(?P<vendor_id>\d+)/$', views.get_service_booking_balances, name='get_service_booking_balances'),
    url(r'^get_current_driver/(?P<vehicle_id>\d+)/$', views.get_current_driver, name='get_current_driver'),
    
    url(r'^new_vehicle_make/$', views.new_vehicle_make, name='new_vehicle_make'),   
    url(r'^new_vehicle_model/$', views.new_vehicle_model, name='new_vehicle_model'),
    url(r'^vehicles/$', views.vehicles, name='vehicles'),
    url(r'^vehicle/uploads$', views.vehicle_uploads, name='vehicle_uploads'),
    url(r'^vehicle/mileage_uploads$', views.mileage_uploads, name='mileage_uploads'),
    url(r'^vehicle/additional_vehicle_information_uploads$', views.additional_vehicle_information_uploads, name='additional_vehicle_information_uploads'),
    url(r'^vehicle/vehicle_service_due$', views.vehicle_service_due, name='vehicle_service_due'),      
    url(r'^vehicles/edit/(?P<vehicle_id>\d+)/$', views.edit_vehicle, name='edit_vehicle'),
    url(r'^vehicles/dashboard/(?P<vehicle_id>\-{0,1}\d+$)', views.vehicle_dashboard, name='vehicle_dashboard'), 
    url(r'^vehicles/purchase_detail/(?P<vehicle_id>\d+)/$', views._load_new_purchase_detail, name='_load_purchase_detail'),
    url(r'^vehicles/add/$', views.edit_vehicle, name='add_vehicle'),
    url(r'^assign_driver/(?P<vehicle_id>\d+)/$', views.assign_driver, name='assign_driver'),
    url(r'^authorize_assigned_driver/(?P<vehicle_id>\d+)/$', views.authorize_assigned_driver, name='authorize_assigned_driver'),
    url(r'^vehicles/summary/(?P<vehicle_id>\-{0,1}\d+$)', views.vehicle_summary, name='vehicle_summary'),
    
    url(r'^fuel_card_admin/$', views.fuel_card_usage, name='fuel_card_usage'),
    url(r'^fuel_card_usage/detail/(?P<fuel_card_id>(\d+))/$',views.detail_fuel_card_usage,name='detail_fuel_card_usage'),
    url(r'^fuel_card_usage/edit/(?P<fuel_card_id>\d+)/$', views.edit_fuel_card_usage, name='edit_fuel_card_usage'),
    url(r'^fuel_card_usage/add/$', views.edit_fuel_card_usage, name='add_fuel_card_usage'),
    url(r'^fuel_card_usage/uploads$', views.fuel_card_uploads, name='fuel_card_uploads'),
    url(r'^fuel_card/edit/(?P<fuel_card_id>\d+)/$', views.edit_fuel_card, name='edit_fuel_card'),
    url(r'^fuel_card/add/$', views.edit_fuel_card, name='add_fuel_card'), 
    url(r'^fuel_cards/$', views.fuel_cards, name='fuel_cards'),
    url(r'^fuel_cards/uploads$', views.fuel_cards_upload, name='fuel_cards_upload'),   

    url(r'^incidents/view/incident-details/(?P<incident_id>\-{0,1}\d+$)', views.view_incident, name='view_incident'), 
    url(r'^incidents/add/(?P<vehicle_driver_id>\-{0,1}\d+$)', views.add_incident, name='add_incident'),
    url(r'^incidents/$', views.view_incidents, name='view_incidents'),
    url(r'^incidents/add/$', views.edit_incident, name='add_incidents'),
    url(r'^incidents/edit/(?P<incident_id>\d+)/$', views.edit_incident, name='edit_incident'),
    url(r'^incident/view/(?P<incident_id>\d+)/$', views.view_incident, name='view_incident'),

    url(r'^incidents/traffic-fines/$', views.traffic_fine_list, name='view_traffic_fines'),
    url(r'^incidents/traffic-fines/add/$', views.edit_traffic_fine, name='add_traffic_fine'),
    url(r'^incidents/traffic-fines/resolve/(?P<incident_id>\d+)/$', views.resolve_fine, name='resolve_fine'),
    url(r'^incidents/traffic-fines/edit/(?P<incident_id>\d+)/$', views.edit_traffic_fine, name='edit_traffic_fine'),
    
    url(r'^document/add/(?P<vehicle_id>\-{0,1}\d+$)', views.add_document, name='add_document'),
    url(r'^document/delete/(?P<vehicle_document_id>\d+)/$', views.document_delete, name='document_delete'),
    url(r'^documents/delete/(?P<incident_document_id>\d+)/$', views.incident_document_delete, name='incident_document_delete'),

    url(r'^photo/add/(?P<vehicle_id>\-{0,1}\d+$)', views.add_photo, name='add_photo'),

    url(r'^insurers$', views.insurers, name='view_insurers'),
    url(r'^insurers/edit/(?P<insurer_id>\d+)/$', views.edit_insurer, name='edit_insurer'),
    url(r'^insurers/add/$', views.edit_insurer, name='add_insurer'),

    url(r'^insurance/vehicles/(?P<insurer_id>\-{0,1}\d+$)', views.insured, name='view_insured'),

    url(r'^documents/(?P<file_id>\d+)/$', views.file_download_task, name='file_download'),

    url(r'^vehicle_maintenance/$', views.vehicle_maintenance, name='vehicle_maintenance'),
    url(r'^vehicle_maintenance/edit/(?P<vehicle_maintenance_id>\d+)/$', views.edit_vehicle_maintenance, name='edit_vehicle_maintenance'),
    url(r'^vehicle_maintenance/add/$', views.edit_vehicle_maintenance, name='add_vehicle_maintenance'),
    url(r'^unassign_vehicle(?P<vehicle_id>\d+)/$', views.unassign_vehicle, name='unassign_vehicle'),

    url(r'^service_booking/$', views.service_booking, name='service_booking'),
    url(r'^resolved_service_booking/$', views.resolved_service_booking, name='resolved_service_booking'),
    url(r'^service_booking/edit/(?P<service_booking_id>\d+)/$', views.edit_service_booking, name='edit_service_booking'),
    url(r'^service_booking/add/$', views.edit_service_booking, name='add_service_booking'),
    url(r'^service_booking_invoice/$', views.service_booking_invoice, name='service_booking_invoice'),
    url(r'^service_booking_invoice/edit/(?P<service_booking_id>\d+)/$', views.edit_service_booking_invoice, name='edit_service_booking_invoice'),
    url(r'^service_booking_invoice/add/$', views.edit_service_booking_invoice, name='add_service_booking_invoice'),

    url(r'^service_providers$', views.vendors, name='view_vendors'),
    url(r'^service_providers/edit/(?P<vendor_id>\d+)/$', views.edit_vendor, name='edit_vendor'),
    url(r'^service_providers/add/$', views.edit_vendor, name='add_vendor'),
    
    url(r'^service_providers$', views.service_providers, name='view_service_providers'),
    url(r'^service_providers/edit/(?P<service_provider_id>\d+)/$', views.edit_service_provider, name='edit_service_provider'),
    url(r'^service_providers/add/$', views.edit_service_provider, name='add_service_provider'),
    

operations/operations/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from django_js_reverse.views import urls_js
from models import RegionAutoComplete,DistrictAutoComplete

urlpatterns = [
    url(r'^region_autocomplete/$', RegionAutoComplete.as_view(), name='region_autocomplete'),
    url(r'^district_autocomplete/$', DistrictAutoComplete.as_view(), name='district_autocomplete'),    
    url(r'^$', views.home, name='home'),
    url(r'^jsreverse/$', urls_js, name='js_reverse'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout,{'next_page':'/'}, name='logout'),

    url(r'^about/$', views.about, name='about'),
    url(r'^users$', views.users, name='users'),
    url(r'^users/fleet-admins/(?P<fleet_administrators>\d+)/$', views.users, name='fleet_admins'),
    url(r'^user/add/$', views.user_edit, name='user_add'),
    url(r'^user/edit/(?P<user_id>\d+)/$', views.user_edit, name='user_edit'),
    
    
    url(r'^', include('fleet_management.urls', namespace='fleetmanagement')),
    url(r'^', include('employees.urls', namespace='employees')), 
    url(r'^', include('facilities.urls', namespace='facilities')),   
    url(r'^', include('assets.urls', namespace='assets')),
    url(r'^', include('api.urls', namespace='api')),

    url(r'^regions$', views.view_regions, name='view_regions'),
    url(r'^branches$', views.view_branches, name='view_branches'),

    url(r'^downloads/$', views.downloads_list, name="view_downloads"),
    url(r'^downloads/(?P<file_id>\d+)/$', views.file_download_task, name="file_download"),

    url(r'^tickets$', views.view_tickets, name='view_tickets'),
    url(r'^tickets/add$', views.edit_ticket, name='add_ticket'),
    url(r'^tickets/edit(?P<ticket_id>\d+)/$', views.edit_ticket, name='edit_ticket'),

    url(r'^service_provider/uploads$', views.service_provider_uploads, name='service_provider_uploads'),
    url(r'^districts/uploads$', views.district_uploads, name='district_uploads'),

    url(r'^accounts/user_profile/(?P<user_id>\-{0,1}\d+$)', views.user_profile, name='user_profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

operations/templates/fleet_management/_incidents_list.html
{% load el_pagination_tags %}
<table id="incidents" class="table table-hover ">
  <tr>{% if incidents %}
    <th>Edit</th>{% endif %}
    <th>Registration Number</th>
    <th>Driver</th>
    <th>Vehicle Make And Model</th>
    <th>Division</th>   
    <th>Incident Type</th>
    <th>Invoice Amount</th>
    <th>Driver Co-Payment</th>
    <th>Total</th>
    <th>Incident Date</th>
    
  </tr>

  {% paginate incidents %}
  {% for incident in incidents %}

  <tr>
    <td><a href="{% url 'fleetmanagement:edit_incident' incident.id %}" data-toggle="" data-toggle="tooltip" data-placement="right" title="Edit Incident"><i class="fas fa-pencil-alt" aria-hidden="true"></i></a></td>
    <td>{{ incident.vehicle.registration_number }}</td>
    {% if incident.driver %}
    <td><a href="{% url 'employees:edit_employee' incident.driver.id %}" data-toggle="" data-toggle="tooltip" data-placement="right" title="View Driver Profile"><i class="fa fa-info-circle" aria-hidden="true"></i>
      {{ incident.driver }}</a></td>
    {% else %}
    <td></td>
    {% endif %}
    <td>{{ incident.vehicle.vehicle_make.make_name }} {{ incident.vehicle.vehicle_model.model_name }}</td>
    <td>{{ incident.vehicle.division |title }}</td>
    <td>{{ incident.incident_type |title }}</td>
    <td></td>
    <td></td>
    <td></td>
    <td>{{ incident.incident_date |date:"d M Y" }}</td>
  </tr>
  {% endfor %}
  <tr>
    <td colspan='13' style="text-align: center">
    <div class="center">
      <div class="pagination">
        {% show_pages %}
      </div>
    </div>
    </td>
  </tr>
</table>

operations/templates/fleet_management/_insurer_list.html
{% load el_pagination_tags %}
<table id="insurers" class="table table-hover ">
  <tr>
    <th>Insurer</th>
    <th>Contact Person</th>
    <th>Address</th>
    <th>Telephone</th>   
    <th>Cell</th>
    <th>Email</th>   
    <th>Insured Vehicles</th>
    
  </tr>

  {% paginate insurers %}
  {% for insurer in insurers %}

  <tr> 
    <td><a href="{% url 'fleetmanagement:edit_insurer' insurer.id %}" data-toggle="" data-toggle="tooltip" data-placement="right" title="Edit insurer"><i class="fas fa-pencil-alt" aria-hidden="true"></i>
      {{ insurer.name }}</a></td>
    <td>{% if insurer.contact_person.first_name %}{{insurer.contact_person.first_name | title }} {% endif %} 
        {% if insurer.contact_person.first_name %}{{ insurer.contact_person.last_name | title }} {% endif %} </td>   
    <td>
      {% if insurer.address.address_line_1 %}{{insurer.address.address_line_1 | title}} {% endif %}  
      {% if insurer.address.address_line_2 %}{{insurer.address.address_line_2 | title}} {% endif %}
      {% if insurer.address.suburb %}{{insurer.address.suburb | title}} {% endif %}
      {% if insurer.address.city %}{{insurer.address.city | title}} {% endif %}
      {% if insurer.address.postal_code %}{{insurer.address.postal_code | title}} {% endif %}
    </td>
    {% if insurer.contact_person.tel_number %}<td>{{insurer.contact_person.tel_number | title}} {% endif %}</td>  
    {% if insurer.contact_person.cell_number %}<td>{{insurer.contact_person.cell_number | title}} {% endif %}</td>
    {% if insurer.contact_person.email %}<td>{{insurer.contact_person.email | title}}{% endif %} </td> 
    {% if insurer.insured_vehicles %}<td>{{ insurer.insured_vehicles }} {% endif %}</td>
  </tr>
  {% endfor %}
  <tr>
    <td colspan='7' style="text-align: center">
    <div class="center">
      <div class="pagination">
        {% show_pages %}
      </div>
    </div>
    </td>
  </tr>
</table>

operations/templates/fleet_management/assign_driver_authorization.html
{% extends "base.html" %}
{% load staticfiles %}

{% load bootstrap4 %}
{% load humanize %}
{% block javascript %}
<!-- <script src="{% static 'js/dropdown.js' %}"></script> -->
{% endblock %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Driver Assigning Authorization:</b>
  </div>
  <div class="panel-body">
    <form method="POST" class="form-2" novalidate>
      {% csrf_token %}
      <div id="edit_fuel_card_tab_content" class="tab-content">
        <div class="tab-pane fade active in" id="details">
          <br>
          <div class='col-lg-6'>{% bootstrap_field vehicle_driver_form.vehicle %}</div>
          <div class='col-lg-6'>{% bootstrap_field vehicle_driver_form.driver %}</div>
          <div class='col-lg-6'>{% bootstrap_field vehicle_driver_form.start_date %}</div>
          <div class='col-lg-6'>{% bootstrap_field vehicle_driver_form.reason %}</div>
      </div>
      <div class="btn-group-horizontal col-lg-12">
        <div class='pull-right'>
          <button type="submit" name="authorize" class="btn btn-primary">
            <i class='fa fa-floppy-o'></i> Authorize
          </button>
          <a href="{% url 'fleetmanagement:vehicles' %}" class="btn btn-primary">
            <i class='fa fa-undo'></i> Cancel
          </a>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

operations/templates/fleet_management/detail_fuel_card_usage.html
{% extends "base.html" %}
{% load staticfiles%}
{% load bootstrap4 %}
{% load humanize %}


{% block content%}
  <script type="text/javascript">
      $(function(){
          $('#id_date_from').val('');
          $('#id_date_to').val('');
      });
  </script>
<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Fuel Usage Detail</b>
    
  </div> 
  <div class="panel-body">

    <form id="fuel_card_usage_list_form" method="GET">
        {% csrf_token %}
         <div class="row">     
        <input name="filter" type="hidden">
        
        <div class='col-lg-4 pull-right'>
          <div class='pull-right'>
            <button type="submit" name="search" class="btn btn-primary" title="Search"><i class="fa fa-search"></i> Search</button>
            <a href="{% url 'fleetmanagement:detail_fuel_card_usage' fuel_card_id %}"  class="btn btn-primary" title="Clear Search"><i class="fa fa-search-minus"></i> Clear</a>           
            <button type="submit" id="load_modal" name="extract" class="btn btn-primary" title="Extract Fuel Cards"><i class="fa fa-download"></i> Extract</button>
            {% if user.is_superuser %}                      
            <a href="{% url 'fleetmanagement:add_fuel_card_usage' %}" class="btn btn-primary" title="Add Fuel Card Usage"><i class="fa fa-plus"></i> Add Usage</a>      
            {% endif %}
          </div>
        </div>
        
      <div class='col-lg-8'>
       
        {% for field in fuel_card_usage_form %}
          <div class='col-lg-4'>
            {% bootstrap_field field layout='inline' %}
          </div>
          {% endfor %}
      </div>       
    </div>
        
    <div class="tab-content">
      <div id="fuel_card" class="tab-pane fade in active">
        {% include 'fleet_management/_fuel_card_usage_detail.html' %}
      </div>
    </div>
    <div class="tab-content" id='fuel_card_document_history'>
      <div class="panel-heading">Document Upload History</div>
      {% include 'fleet_management/widgets/_fuel_card_document_history.html' %}
    </div>      
    <div class="modal fade" id="extract_modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">      
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modalLabel"><i class="fa fa-info-circle" aria-hidden="true"></i> Extract Fuel Card(s)</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <b> Are you sure you want to download the extract</b>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="submit" name="extract" id="extract" class="btn btn-primary">Ok</button>
            </div>
          </div>
        </div>      
    </div>
   </form>      
  </div>
</div>

{% endblock %}

operations/templates/fleet_management/fuel_card_uploads.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% load humanize %}

{% block content%}
<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Upload Fuel Card Usage</b>
  </div>

  <div class="panel-body">
    <form method='post' enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <br>
      <button class="btn btn-primary pull-right">Updating Fuel Card Usage</button>
    </form>
  </div>
</div>
{% endblock %}

operations/templates/fleet_management/fuel_cards.html
{% extends "base.html" %}
{% load staticfiles%}
{% load bootstrap4 %}
{% load humanize %}
{% block javascript %}
  <script src="{% static 'js/fuel_cards.js' %}"></script>
{% endblock %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Fuel Cards List</b>
    
  </div> 
  <div class="panel-body">

    <form id="fuel_card_usage_filter_form" method="GET">
        {% csrf_token %}

    <div class="row">     
        <input name="filter" type="hidden">
        
        <div class='col-lg-3 pull-right'>
          <div class='pull-right'>
            <button type="submit" name="search" class="btn btn-primary" title="Search"><i class="fa fa-search"></i> Search</button>
            
            <a href="{% url 'fleetmanagement:fuel_cards' %}"  class="btn btn-primary" title="Clear Search"><i class="fa fa-search-minus"></i> Clear</a>
            
            <button type="submit" id="load_modal" class="btn btn-primary" title="Extract Fuel Card Usage"><i class="fa fa-download"></i> Extract</button>
            <a href="{% url 'fleetmanagement:add_fuel_card' %}" class="btn btn-primary" title="Add Fuel Card"><i class="fa fa-plus"></i> Add Card</a>                     
          </div>
        </div>
        
      <div class='col-lg-9'>
        <div class='col-lg-3'>
          {% bootstrap_field fuel_card_filter_form.card_number layout='inline' %}
        </div>
        <div class='col-lg-3'>
          {% bootstrap_field fuel_card_filter_form.card_type layout='inline' %}
        </div>
        <div class='col-lg-3'>
          {% bootstrap_field fuel_card_filter_form.date_from layout='inline' %}
        </div>
         <div class='col-lg-3'>
          {% bootstrap_field fuel_card_filter_form.date_to layout='inline' %}
        </div>
        <div class='col-lg-3'>
          {% bootstrap_field fuel_card_filter_form.vehicle layout='inline' %}
        </div>
        <div class='col-lg-3'>
          {% bootstrap_field fuel_card_filter_form.driver layout='inline' %}
        </div>
        <div class='col-lg-3'>
          {% bootstrap_field fuel_card_filter_form.supplier layout='inline' %}
        </div>
        <div class='col-lg-3'>
          {% bootstrap_field fuel_card_filter_form.status layout='inline' %}
        </div>
      </div>       
    </div>
    
    <div class="tab-content">
      <div id="fuel_card" class="tab-pane fade in active">
        {% include 'fleet_management/_fuel_cards_list.html' %}

      </div>
    </div>

    <div class="modal fade" id="extract_modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">      
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modalLabel"><i class="fa fa-info-circle" aria-hidden="true"></i> Extract Fuel Card(s)</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <b> Are you sure you want to download the extract</b>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="submit" name="extract" id="extract" class="btn btn-primary">Ok</button>
            </div>
          </div>
        </div>     
    </div>
  </form>
  </div>
</div>
{% endblock %}

operations/templates/fleet_management/vehicle_uploads.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% load humanize %}

{% block content%}
<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Upload Vehicles</b>
  </div>
  
  <div class="panel-body">
    <form method='post' enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <br>
      <button class="btn btn-primary pull-right">Update Vehicles</button>
    </form>
  </div>
</div>
{% endblock %}